name: BloraStorage
version: '${version}'
main: net.bloret.blorastorage.BloraStorage
api-version: '1.20'
authors: [Rhedar]
description: A plugin that creates a storage for players to pass items between servers.
website: https://www.bloret.net
commands:
  blorastorage:
    description: Access your personal storage
    usage: /blorastorage <args>
    aliases: [bs]